"""Sample weights from overlapping labels (AFML Ch. 4).

Event labels generated by the triple-barrier method have overlapping
lifetimes [t0, t1]. Training as if they were IID produces redundancy and a
false sense of sample size. We compute:

- concurrency c(t): number of events live at time t
- uniqueness u_i = mean over t in [t0_i, t1_i] of 1/c(t)
- return-attribution weight w_i = |sum_t r(t)/c(t)| for t in event lifetime

Both are passed as `sample_weight` to the ML model.
"""
from __future__ import annotations

import numpy as np
import pandas as pd


def concurrency(close_index: pd.DatetimeIndex, events: pd.DataFrame) -> pd.Series:
    """Number of label lifetimes covering each bar."""
    c = pd.Series(0, index=close_index, dtype=int)
    for t0, t1 in events["t1"].items():
        if pd.isna(t1):
            continue
        c.loc[t0:t1] += 1
    return c.replace(0, 1)


def average_uniqueness(events: pd.DataFrame, conc: pd.Series) -> pd.Series:
    """u_i in (0, 1]. 1 means no overlap, ~0 means heavily redundant."""
    u = pd.Series(0.0, index=events.index)
    for t0, t1 in events["t1"].items():
        if pd.isna(t1):
            continue
        window = conc.loc[t0:t1]
        u.loc[t0] = float((1.0 / window).mean())
    return u


def return_attribution_weights(
    close: pd.Series, events: pd.DataFrame, conc: pd.Series
) -> pd.Series:
    """Weight each label by the magnitude of the returns it is credited with.

    Following AFML 4.10, distribute each bar's return equally among the
    events live at that bar, then sum the absolute contributions per event.
    """
    log_ret = np.log(close / close.shift(1)).fillna(0.0)
    w = pd.Series(0.0, index=events.index)
    for t0, t1 in events["t1"].items():
        if pd.isna(t1):
            continue
        attribution = (log_ret.loc[t0:t1] / conc.loc[t0:t1]).sum()
        w.loc[t0] = abs(float(attribution))
    # Normalise to mean 1 so it plays well with sklearn sample_weight
    if w.sum() > 0:
        w = w * (len(w) / w.sum())
    return w


def sequential_bootstrap(
    events: pd.DataFrame,
    conc: pd.Series,
    n_samples: int | None = None,
    random_state: int = 0,
) -> np.ndarray:
    """Sequential bootstrap (AFML 4.5): each draw re-weights the sampling
    distribution by the average uniqueness given what is already drawn.

    Simplified implementation for performance: uses average_uniqueness as a
    static prior, which is the first iterate of the recursive scheme.
    """
    rng = np.random.default_rng(random_state)
    u = average_uniqueness(events, conc).to_numpy()
    u = np.clip(u, 1e-6, None)
    probs = u / u.sum()
    n = n_samples or len(events)
    return rng.choice(len(events), size=n, replace=True, p=probs)
